
server:
  port: 5000
  servlet:
    context-path: /checkin-service
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: true

spring:
  application:
    name: checkin-service
  main:
    allow-bean-definition-overriding: true
  jpa:
    open-in-view: true
    hibernate:
      id:
        new_generator_mappings: true
      ddl-auto: update
      naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
    properties:
      hibernate:

        enable_lazy_load_no_trans: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:checkin_dev
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
springdoc:
  swagger-ui:
    title: Checkin Service
    description: Microservice responsible for Checkin Services
    version: 1.0.0
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

